[[main]]
  identifier = "archive"
  name = "ğŸ—„ï¸ &nbsp;Archivo"
  url = "archive"
  weight = 1

[[main]]
  identifier = "posts"
  name = "ğŸ“ &nbsp;Entradas"
  url = "posts"
  weight = 2

[[main]]
  parent = "posts"
  identifier = "categories"
  name = "ğŸ—‚ï¸ &nbsp;CategorÃ­as"
  url = "categories"
  weight = 3

[[main]]
  parent = "posts"
  identifier = "tags"
  name = "ğŸ·ï¸ &nbsp;Etiquetas"
  url = "tags"
  weight = 4

[[main]]
  identifier = "books"
  name = "ğŸ“š &nbsp;Libros"
  url = "books"
  weight = 5

[[main]]
  identifier = "about"
  name = "â„¹ï¸ &nbsp;Sobre mÃ­"
  url = "about"
  weight = 6
