[[main]]
  identifier = "archive"
  name = "ğŸ—„ï¸ &nbsp;Archive"
  url = "archive"
  weight = 1

[[main]]
  identifier = "posts"
  name = "ğŸ“ &nbsp;Posts"
  url = "posts"
  weight = 2

[[main]]
  parent = "posts"
  name = "ğŸ—‚ï¸ &nbsp;Categories"
  url = "categories"
  weight = 3

[[main]]
  parent = "posts"
  name = "ğŸ·ï¸ &nbsp;Tags"
  url = "tags"
  weight = 4

[[main]]
  identifier = "books"
  name = "ğŸ“š &nbsp;Books"
  url = "books"
  weight = 5

[[main]]
  identifier = "about"
  name = "â„¹ï¸ &nbsp;About"
  url = "about"
  weight = 6
